apiVersion: apps/v1
kind: Deployment
metadata:
  name:  RoomService-deployment
  labels:
    app:  RoomService
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  RoomService  
  template:
    metadata:
      labels:
        app:  RoomService
    spec:
      containers:
      - name: MyDNAzureCR0905
        image: mydnazurecr0705.azurecr.io/azurecontainerrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name:  RoomServicesvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app:  RoomService
